using MicroS_Common.Types;
using MicroS_Common.RestEase;
using RestEase;
using System;
using System.Threading.Tasks;
using weerp.domain.tiers.Dto;
using weerp.domain.tiers.Queries;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Mon Jun 01 2020 10:23:40 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.api.Services
{
    /// <summary>
    /// Tier Service created by <see cref="https://www.nuget.org/packages/RestEase/">Restease</see>
    /// </summary>
    [ServiceForwarder("tiers-service")]
    [SerializationMethods(Query = QuerySerializationMethod.Serialized)]
    public partial interface ITiersService
    {
        /// <summary>
        /// Get tier by its Id
        /// </summary>
        /// <param name="id">the id of  Tier</param>
        /// <returns>TierDto</returns>
        [AllowAnyStatusCode]
        [Get("tiers/{id}")]
        Task<TierDto> GetAsync([Path] Guid id);


         /// <summary>
        /// Get list of tiers by BrowseTiers Query
        /// </summary>
        /// <param name="query">The Browse tiers query</param>
        /// <returns>a list of TierDto</returns>
        [AllowAnyStatusCode]
        [Get("tiers")]
        Task<PagedResult<TierDto>> BrowseAsync([Query] BrowseTiers query);
    }
}
