using MicroS_Common.Mvc;
using MicroS_Common.RabbitMq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OpenTracing;
using System;
using System.Threading.Tasks;
using weerp.api.Framework;
using weerp.api.Services;
using weerp.domain.tiers.Messages.Commands;
using weerp.domain.tiers.Queries;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Mon Jun 01 2020 10:23:40 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.api.Controllers
{
    /// <summary>
    /// Tier Controller that represent tha main API layer
    /// on wich each request must be made
    /// </summary>
    [AdminAuth]
    [Route("tiers")]
    public partial class TiersController : BaseController
    {
        #region private varaibles
        private readonly ITiersService _tiersService;
        private readonly ILogger<CreateTier> _logger;
        #endregion

        #region constructors
        public TiersController(IBusPublisher busPublisher, ITracer tracer,
            ITiersService tiersService,ILogger<CreateTier>logger) : base(busPublisher, tracer)
        {
            _tiersService = tiersService;
            _logger = logger;
        }
        #endregion

        #region public functions
         /// <summary>
        ///  Make a get query 
        /// </summary>
        /// <param name="query">The Query</param>
        /// <returns>A list of result</returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Get([FromQuery] BrowseTiers query)
            => Collection(await _tiersService.BrowseAsync(query));

        /// <summary>
        /// Search an Unique tier based on its id
        /// </summary>
        /// <param name="id">The Id to search</param>
        /// <returns>The tier</returns>
        [HttpGet("{id}")]
        [AllowAnonymous]
        public async Task<IActionResult> Get(Guid id)
            => Single(await _tiersService.GetAsync(id));

        /// <summary>
        ///  Create a new tier
        /// </summary>
        /// <param name="command">The Create Command</param>
        /// <returns>Accepted response: The the operation Service</returns>
        [HttpPost]
        public async Task<IActionResult> Post(CreateTier command)
            => await SendAsync(command.BindId(c => c.Id,_logger),  resourceId: command.Id, resource: "tiers");

        /// <summary>
        /// Update a tier
        /// </summary>
        /// <param name="id">the id of tier to update</param>
        /// <param name="command">The Update Command</param>
        /// <returns>Accepted response: The the operation Service</returns>
        [HttpPut("{id}")]
        public async Task<IActionResult> Put(Guid id, UpdateTier command)
            => await SendAsync(command.Bind(c => c.Id, id),resourceId: command.Id, resource: "tiers");

        /// <summary>
        /// Delete a tier
        /// </summary>
        /// <param name="id">the id of tier to delete</param>
        /// <returns>Accepted response: The the operation Service</returns>
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(Guid id)
            => await SendAsync(new DeleteTier(id));

        #endregion
    }
}
