#region using
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using MicroS_Common;
using MicroS_Common.Types;
using MicroS_Common.Controllers;
using MicroS_Common.Dispatchers;
using weerp.domain.tiers.Dto;
using weerp.domain.tiers.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:29:59 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.Services.Products.Controllers
{
    [Route("tiers")]
    public partial class TiersController : BaseController
    {
        public TiersController(IDispatcher dispatcher,IConfiguration config,IOptions<AppOptions> appOptions) : base(dispatcher,config,appOptions)
        {
        }

        [HttpGet("")]
        public async Task<ActionResult<PagedResult<TierDto>>> Get([FromQuery] BrowseTiers query)
            => Collection(await QueryAsync(query));

        [HttpGet("{id}")]
        public async Task<ActionResult<TierDto>> Get([FromRoute] GetTier query)
            => Single(await QueryAsync(query));
        
        
    }
}