using System;
using System.Collections.Generic;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:29:59 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.domain.tiers.Messages.Events
{
    public class TierUpdated : TierCreated
    {
        public TierUpdated(Guid id,string name,string title,int number,string description) 
        : base(id,name,title,number,description)
        {
        }
    }
}
