using System;

using MicroS_Common.Mongo;
using MongoDB.Bson.Serialization.Attributes;


using MicroS_Common.Types;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:29:58 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.domain.tiers.Domain
{
    [MongoDocument("tier")]
    public partial class Tier  :BaseEntity
    {
        #region private variables
        
        
        #endregion


        #region public properties
         [BsonElement("name")]
public string Name {get;set;}
[BsonElement("title")]
public string Title {get;set;}
[BsonElement("number")]
public int Number {get;set;}
[BsonElement("description")]
public string Description {get;set;}

         
        #endregion

        #region Constructeur
        public Tier():base(){}
        
        public Tier(string name,string title,int number,string description)
            : base()
        {
            Name =name; 
Title =title; 
Number =number; 
Description =description; 
        }
        
        #endregion
        #region public functions
        #endregion

    }
}
