using System;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:29:59 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.domain.tiers.Messages.Commands
{

    public class CreateTier : TierBaseCommand
    {
        
        public override Guid Id { get; set; }
        
        public string Name {get;}
public string Title {get;}
public int Number {get;}
public string Description {get;}
        



        public CreateTier(
            Guid id,string name,string title,int number,string description) : base()
        {
            
            Id = id;
            
            Name =name; 
Title =title; 
Number =number; 
Description =description; 

           
        }
    }
}
