#region using
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using weerp.domain.Products.Domain;
using weerp.domain.Products.Dto;
using weerp.domain.Products.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Wed May 13 2020 11:51:54 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.Services.Products.Repositories
{


    #region interface
    /// <summary>
    /// Article Repository for intereaction with database
    /// </summary>
    public interface IBrowseProductRepository : IBrowseRepository<Product, BrowseProducts, ProductDto> { }
    #endregion 

    #region Implementation
    /// <summary>
    /// Article Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseProductRepository))]
    public partial class ArticleRepository : BrowseRepository<Product, BrowseProducts, ProductDto>, IBrowseProductRepository
    {
        public ArticleRepository(IMongoRepository<Product> repository, IMapper mapper) : base(repository, mapper) { }

    }
    #endregion
}
