
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using weerp.domain.tiers.Domain;
using weerp.domain.tiers.Dto;
using weerp.domain.tiers.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:29:59 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.Services.Products.Repositories
{    

    #region interface
    /// <summary>
    /// Tier Repository for intereaction with database
    /// </summary>
    public interface IBrowseTierRepository : IBrowseRepository<Tier,BrowseTiers,TierDto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// Tier Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseTierRepository))]
    public partial class TierRepository : BrowseRepository<Tier,BrowseTiers,TierDto>,IBrowseTierRepository 
    {
        public TierRepository(IMongoRepository<Tier> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}