using AutoMapper;
using MicroS_Common.Handlers;
using Microsoft.Extensions.Logging;
using weerp.domain.tiers.Domain;
using weerp.domain.tiers.Dto;
using weerp.domain.tiers.Queries;
using weerp.Services.Products.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:24:15 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.Services.Products.Handlers
{
    /// <summary>
    /// Browse Tier Handler
    /// </summary>
    public partial class BrowseTierHandlerGen : BaseBrowseHandler<Tier, BrowseTiers, TierDto, IBrowseTierRepository>
    {
        public BrowseTierHandlerGen(IBrowseTierRepository repository, IMapper mapper,ILogger<BrowseTierHandlerGen> logger) : base(repository, mapper,logger){}
    }
}
