using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.RabbitMq;
using MicroS_Common.Repository;
using MicroS_Common.Types;
using System.Threading.Tasks;
using weerp.domain.tiers.Domain;
using weerp.domain.tiers.Messages.Commands;
using weerp.domain.tiers.Messages.Events;
using weerp.Services.Products.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:29:59 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.Services.Products.Handlers
{
    /// <summary>
    /// Update Tier Handler
    /// </summary>
    public partial class UpdateTierHandler : DomainCommandHandler<UpdateTier, Tier>
    {
        #region Constructors
        public UpdateTierHandler(
            IBusPublisher busPublisher, 
            IMapper mapper, 
            IBrowseTierRepository repo) : base(busPublisher, mapper, repo)
        {
        }
        #endregion
        #region Protected Overrides functions
        /// <summary>
        /// Check if the model exist by Command
        /// </summary>
        /// <param name="command">The command in wich information can be use do check if the model exist in database</param>
        /// <returns>Nothing</returns>
        protected override async Task CheckExist(Tier domain)
        {
            if (!await Repository.ExistsAsync(domain.Id))
            {
                throw new MicroSException("tier_not_found",$"Tier with id: '{domain.Id}' was not found.");
            }
        }
        #endregion
        #region Public Overrides functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public override async Task HandleAsync(UpdateTier command, ICorrelationContext context)
        {
            
            await base.HandleAsync(command, context);
            var product = GetDomainObject(command);
            await Repository.UpdateAsync(product);
            await BusPublisher.PublishAsync(CreateEvent<TierUpdated>(command), context);
        }
        #endregion
    }
}
