using System;
using System.Collections.Generic;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun May 31 2020 14:29:59 GMT+0200 (GMT+02:00)
/// </summary>
namespace weerp.domain.tiers.Dto
{
    public partial class TierDto
    {

        #region private variables
        
        #endregion

        #region public properties
        
         public Guid Id { get; set; }
        
        
        public string Name  {get;set;}
        
        public string Title  {get;set;}
        
        public int Number  {get;set;}
        
        public string Description  {get;set;}
        
        
        #endregion


    }
}
